#!/usr/bin/env python3
"""
Independent log parser fixtures for testing log_aggregator.py

These fixtures are hand-written representative log lines that validate
the main parser paths without relying on parser-generated samples.
This addresses the false-pass issue where test data was generated by
the same parser logic being tested.
"""

# JSON Log Fixtures
# These are realistic JSON log lines from various services
JSON_FIXTURES = [
    # Standard JSON log with timestamp field
    {
        "line": '{"timestamp": "2024-01-15T10:30:45Z", "level": "info", "service": "api-gateway", "message": "Request processed successfully"}',
        "expected": {
            "timestamp": "2024-01-15T10:30:45Z",
            "level": "info",
            "service": "api-gateway",
            "message": "Request processed successfully",
            "format": "json"
        }
    },
    # JSON with time field instead of timestamp
    {
        "line": '{"time": "2024-01-15T10:30:45Z", "severity": "error", "logger": "auth-service", "msg": "Authentication failed for user"}',
        "expected": {
            "timestamp": "2024-01-15T10:30:45Z",
            "level": "error",
            "service": "auth-service",
            "message": "Authentication failed for user",
            "format": "json"
        }
    },
    # JSON with @timestamp (Elasticsearch format)
    {
        "line": '{"@timestamp": "2024-01-15T10:30:45Z", "lvl": "debug", "app": "payment-processor", "event": "Payment webhook received"}',
        "expected": {
            "timestamp": "2024-01-15T10:30:45Z",
            "level": "debug",
            "service": "payment-processor",
            "message": "Payment webhook received",
            "format": "json"
        }
    },
    # Minimal JSON log
    {
        "line": '{"level": "warn", "service": "cache-service", "message": "Cache miss for key: user_session_123"}',
        "expected": {
            "timestamp": None,
            "level": "warn",
            "service": "cache-service",
            "message": "Cache miss for key: user_session_123",
            "format": "json"
        }
    },
]

# Plain Text Log Fixtures
# These are realistic plain text log lines with various formats
TEXT_FIXTURES = [
    # Service in brackets (without timestamp to avoid pattern conflicts)
    # Note: \w+ only matches word characters (letters, digits, underscore), not hyphens
    {
        "line": "[apigateway] INFO Request processed successfully",
        "expected": {
            "format": "text",
            "level": "info",
            "service": "apigateway",
            "message": "[apigateway] INFO Request processed successfully"
        }
    },
    # Service in brackets with error level
    {
        "line": "[authservice] ERROR Authentication failed for user",
        "expected": {
            "format": "text",
            "level": "error",
            "service": "authservice",
            "message": "[authservice] ERROR Authentication failed for user"
        }
    },
    # Uppercase service followed by colon
    {
        "line": "PAYMENT: WARN Payment processing timeout",
        "expected": {
            "format": "text",
            "level": "warn",
            "service": "PAYMENT",
            "message": "PAYMENT: WARN Payment processing timeout"
        }
    },
    # Plain text without explicit service (service extraction will fail)
    {
        "line": "DEBUG Database query executed in 45ms",
        "expected": {
            "format": "text",
            "level": "debug",
            "service": None,
            "message": "DEBUG Database query executed in 45ms"
        }
    },
]

# Nginx Log Fixtures
# These are realistic nginx access log lines
NGINX_FIXTURES = [
    # Successful GET request
    {
        "line": '192.168.1.100 - - [15/Jan/2024:10:30:45 +0000] "GET /api/users HTTP/1.1" 200 1234 "https://example.com" "Mozilla/5.0"',
        "expected": {
            "format": "nginx",
            "level": "info",
            "service": "nginx",
            "fields": {
                "remote_addr": "192.168.1.100",
                "remote_user": "-",
                "request": "GET /api/users HTTP/1.1",
                "status": 200,
                "body_bytes": "1234",
                "referer": "https://example.com",
                "user_agent": "Mozilla/5.0"
            }
        }
    },
    # 404 Not Found (warning level)
    {
        "line": '10.0.0.50 - - [15/Jan/2024:10:30:45 +0000] "GET /nonexistent HTTP/1.1" 404 512 "-" "curl/7.68.0"',
        "expected": {
            "format": "nginx",
            "level": "warn",
            "service": "nginx",
            "fields": {
                "remote_addr": "10.0.0.50",
                "remote_user": "-",
                "request": "GET /nonexistent HTTP/1.1",
                "status": 404,
                "body_bytes": "512",
                "referer": "-",
                "user_agent": "curl/7.68.0"
            }
        }
    },
    # 500 Internal Server Error (error level)
    {
        "line": '172.16.0.100 - - [15/Jan/2024:10:30:45 +0000] "POST /api/payment HTTP/1.1" 500 256 "https://app.example.com/checkout" "Mozilla/5.0 (Windows NT 10.0)"',
        "expected": {
            "format": "nginx",
            "level": "error",
            "service": "nginx",
            "fields": {
                "remote_addr": "172.16.0.100",
                "remote_user": "-",
                "request": "POST /api/payment HTTP/1.1",
                "status": 500,
                "body_bytes": "256",
                "referer": "https://app.example.com/checkout",
                "user_agent": "Mozilla/5.0 (Windows NT 10.0)"
            }
        }
    },
]

# Malformed/Unsupported Log Lines
# These should not crash the parser
MALFORMED_FIXTURES = [
    # Invalid JSON
    {"line": '{"invalid": json structure}', "should_parse": False},
    # Empty line
    {"line": "", "should_parse": False},
    # Nginx line with missing fields
    {"line": "192.168.1.100 - incomplete", "should_parse": False},
    # Random text without recognizable patterns
    {"line": "This is just some random text without log structure", "should_parse": False},
    # Binary-like content
    {"line": "\x00\x01\x02\x03\x04\x05", "should_parse": False},
]